import type { WidgetType, WidgetDefinition } from '../types/pdf-layout'

export const WIDGET_DEFINITIONS: Record<WidgetType, WidgetDefinition> = {
  // ─── Tables ─────────────────────────────────────────────────────
  executive_summary: {
    type: 'executive_summary',
    label: 'Executive Summary',
    category: 'tables',
    icon: 'FileText',
    defaultColSpan: 2, defaultRowSpan: 2,
    minColSpan: 2, maxColSpan: 3, minRowSpan: 2, maxRowSpan: 3,
    dataDependency: 'report',
  },
  budget_vs_actual: {
    type: 'budget_vs_actual',
    label: 'Budget vs Actual',
    category: 'tables',
    icon: 'Table2',
    defaultColSpan: 2, defaultRowSpan: 3,
    minColSpan: 2, maxColSpan: 3, minRowSpan: 2, maxRowSpan: 3,
    dataDependency: 'report',
  },
  ytd_summary: {
    type: 'ytd_summary',
    label: 'YTD Summary',
    category: 'tables',
    icon: 'Table2',
    defaultColSpan: 2, defaultRowSpan: 3,
    minColSpan: 2, maxColSpan: 3, minRowSpan: 2, maxRowSpan: 3,
    dataDependency: 'report',
  },
  full_year_projection: {
    type: 'full_year_projection',
    label: 'Full Year Projection',
    category: 'tables',
    icon: 'Calendar',
    defaultColSpan: 3, defaultRowSpan: 3,
    minColSpan: 3, maxColSpan: 3, minRowSpan: 2, maxRowSpan: 3,
    dataDependency: 'fullYear',
  },
  subscription_detail: {
    type: 'subscription_detail',
    label: 'Subscription Detail',
    category: 'tables',
    icon: 'CreditCard',
    defaultColSpan: 2, defaultRowSpan: 2,
    minColSpan: 2, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 3,
    dataDependency: 'subscriptions',
  },
  wages_detail: {
    type: 'wages_detail',
    label: 'Wages Detail',
    category: 'tables',
    icon: 'Users',
    defaultColSpan: 2, defaultRowSpan: 2,
    minColSpan: 2, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 3,
    dataDependency: 'wages',
  },
  cashflow_forecast_table: {
    type: 'cashflow_forecast_table',
    label: 'Cashflow Forecast Table',
    category: 'tables',
    icon: 'TrendingUp',
    defaultColSpan: 3, defaultRowSpan: 3,
    minColSpan: 3, maxColSpan: 3, minRowSpan: 2, maxRowSpan: 3,
    dataDependency: 'cashflow',
  },

  // ─── P&L Charts ─────────────────────────────────────────────────
  chart_revenue_breakdown: {
    type: 'chart_revenue_breakdown',
    label: 'Revenue Breakdown',
    category: 'pl_charts',
    icon: 'PieChart',
    defaultColSpan: 1, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 2, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'report',
  },
  chart_break_even: {
    type: 'chart_break_even',
    label: 'Break Even Analysis',
    category: 'pl_charts',
    icon: 'Target',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'fullYear',
  },
  chart_revenue_vs_expenses: {
    type: 'chart_revenue_vs_expenses',
    label: 'Revenue vs Expenses',
    category: 'pl_charts',
    icon: 'TrendingUp',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'fullYear',
  },
  chart_variance_heatmap: {
    type: 'chart_variance_heatmap',
    label: 'Variance Heatmap',
    category: 'pl_charts',
    icon: 'Grid3x3',
    defaultColSpan: 2, defaultRowSpan: 2,
    minColSpan: 2, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 3,
    dataDependency: 'fullYear',
  },
  chart_budget_burn_rate: {
    type: 'chart_budget_burn_rate',
    label: 'Budget Burn Rate',
    category: 'pl_charts',
    icon: 'Flame',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'report',
  },

  // ─── Cashflow Charts ────────────────────────────────────────────
  chart_cash_runway: {
    type: 'chart_cash_runway',
    label: 'Cash Runway',
    category: 'cashflow_charts',
    icon: 'Timer',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'cashflow',
  },
  chart_cumulative_net_cash: {
    type: 'chart_cumulative_net_cash',
    label: 'Cumulative Net Cash',
    category: 'cashflow_charts',
    icon: 'BarChart3',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'cashflow',
  },
  chart_working_capital_gap: {
    type: 'chart_working_capital_gap',
    label: 'Working Capital Gap',
    category: 'cashflow_charts',
    icon: 'AlertTriangle',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'cashflow',
  },
  chart_cashflow_forecast: {
    type: 'chart_cashflow_forecast',
    label: 'Cashflow Forecast Chart',
    category: 'cashflow_charts',
    icon: 'LineChart',
    defaultColSpan: 2, defaultRowSpan: 2,
    minColSpan: 2, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 3,
    dataDependency: 'cashflow',
  },

  // ─── People / Subscriptions Charts ──────────────────────────────
  chart_team_cost_pct: {
    type: 'chart_team_cost_pct',
    label: 'Team Cost %',
    category: 'people_charts',
    icon: 'Users',
    defaultColSpan: 1, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 2, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'fullYear',
  },
  chart_cost_per_employee: {
    type: 'chart_cost_per_employee',
    label: 'Cost Per Employee',
    category: 'people_charts',
    icon: 'DollarSign',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'wages',
  },
  chart_subscription_creep: {
    type: 'chart_subscription_creep',
    label: 'Subscription Creep',
    category: 'people_charts',
    icon: 'TrendingUp',
    defaultColSpan: 2, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 3, minRowSpan: 1, maxRowSpan: 2,
    dataDependency: 'subscriptions',
  },

  // ─── KPI Cards ──────────────────────────────────────────────────
  kpi_revenue: {
    type: 'kpi_revenue',
    label: 'Revenue KPI',
    category: 'kpi_cards',
    icon: 'DollarSign',
    defaultColSpan: 1, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 1, minRowSpan: 1, maxRowSpan: 1,
    dataDependency: 'report',
  },
  kpi_gross_profit: {
    type: 'kpi_gross_profit',
    label: 'Gross Profit KPI',
    category: 'kpi_cards',
    icon: 'TrendingUp',
    defaultColSpan: 1, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 1, minRowSpan: 1, maxRowSpan: 1,
    dataDependency: 'report',
  },
  kpi_net_profit: {
    type: 'kpi_net_profit',
    label: 'Net Profit KPI',
    category: 'kpi_cards',
    icon: 'Activity',
    defaultColSpan: 1, defaultRowSpan: 1,
    minColSpan: 1, maxColSpan: 1, minRowSpan: 1, maxRowSpan: 1,
    dataDependency: 'report',
  },
}

export const WIDGET_CATEGORIES: { key: WidgetDefinition['category']; label: string }[] = [
  { key: 'tables', label: 'Tables' },
  { key: 'pl_charts', label: 'P&L Charts' },
  { key: 'cashflow_charts', label: 'Cashflow Charts' },
  { key: 'people_charts', label: 'People & Subscriptions' },
  { key: 'kpi_cards', label: 'KPI Cards' },
]

export function getWidgetsByCategory(category: WidgetDefinition['category']): WidgetDefinition[] {
  return Object.values(WIDGET_DEFINITIONS).filter(w => w.category === category)
}
