export { default as FinancialGoalsSection } from './FinancialGoalsSection'
export { default as CoreMetricsSection } from './CoreMetricsSection'
export { default as KPISection } from './KPISection'
export { getYearLabel, FINANCIAL_METRICS } from './types'
export type { YearLabel, MetricConfig } from './types'
