/**
 * Where a monthly-report viewer lands, and where the report's own controls are
 * drawn, for a business whose report consolidates several Xero orgs.
 *
 * Pure, and kept out of page.tsx for the reason multi-currency-toast is: the
 * rules can be tested without mounting the page (30+ heavy imports).
 *
 * IICT-01: IICT Group has an HKD org, so the multi-currency redirect moved every
 * coach from Budget vs Actual to the Consolidated P&L tab. Generate Report was
 * drawn on Budget vs Actual only — and Export, Finalise and Memo appear only
 * once a report exists — so no coach could produce an IICT pack at all.
 */
import type { ReportTab } from '../types'

export type ReportViewerRole = 'coach' | 'super_admin' | 'client'

/** The tabs that sum every org's figures as they are, and their FX-translated twins. */
const CONSOLIDATED_EQUIVALENT: Partial<Record<ReportTab, ReportTab>> = {
  report: 'consolidated',
  'balance-sheet': 'balance-sheet-consolidated',
  cashflow: 'cashflow-consolidated',
}

/**
 * The tab a multi-currency business's viewer is moved to, or null to stay.
 *
 * A consolidation parent's Budget vs Actual tab is not an unconverted sum:
 * useMonthlyReport generates it through the consolidation engine, each org
 * translated at the month's rate. So it stays where it is. While the connection
 * count is still being read (null) it stays too — moving a coach then would
 * strand them on the tab it is about to turn out they did not need.
 *
 * Every other case is the redirect as it always was: the single-entity Balance
 * Sheet and Cashflow tabs, and a multi-currency business that is not a
 * consolidation parent. Clients are never moved — the consolidated tabs are a
 * coach/admin view.
 */
export function multiCurrencyRedirectTarget(input: {
  activeTab: ReportTab
  isMultiCurrency: boolean
  /** null while the connection count is still being read. */
  isConsolidationGroup: boolean | null
  userRole: ReportViewerRole
}): ReportTab | null {
  if (!input.isMultiCurrency || input.userRole === 'client') return null
  if (input.activeTab === 'report' && input.isConsolidationGroup !== false) return null
  return CONSOLIDATED_EQUIVALENT[input.activeTab] ?? null
}

/**
 * Whether the tab on screen draws the reconciliation gate, Generate Report and
 * the report's error.
 *
 * Budget vs Actual always has. The Consolidated P&L tab of a consolidation
 * parent has them too: coaches have been landing there (the old redirect saved
 * it as their tab), and a tab that shows a group's figures without a way to
 * generate its report is the dead end IICT hit. A viewer who cannot see the
 * consolidated tab — every single-entity business, every client — sees the
 * controls exactly where they were.
 */
export function showsReportControls(activeTab: ReportTab, canSeeConsolidated: boolean): boolean {
  return activeTab === 'report' || (activeTab === 'consolidated' && canSeeConsolidated)
}

/**
 * Whether Budget vs Actual carries the missing-exchange-rate banner (and so
 * loads the consolidation that knows which rates are missing).
 *
 * The Consolidated P&L tab has always carried it, and that is where the
 * redirect put a multi-currency business's coach. They land on Budget vs Actual
 * now, which prints the same translated figures — so a month without a rate
 * says so on the tab they are looking at, not only on one they have left.
 * All-AUD businesses have nothing to translate and are unchanged.
 */
export function showsFxRatesOnReportTab(
  activeTab: ReportTab,
  isMultiCurrency: boolean,
  canSeeConsolidated: boolean,
): boolean {
  return activeTab === 'report' && isMultiCurrency && canSeeConsolidated
}

/**
 * DRG-51: whether this viewer can generate the report.
 *
 * A consolidated report is generated by the coach — the route that builds it
 * refuses anyone else, as it refuses the per-entity page. A client of a
 * consolidation parent was shown a Generate button that could only fail. They
 * are told who prepares it instead, and where the saved reports are.
 */
export function generateAccess(
  isConsolidationGroup: boolean | null,
  userRole: ReportViewerRole,
): 'generate' | 'coach_only' {
  return isConsolidationGroup === true && userRole === 'client' ? 'coach_only' : 'generate'
}

export const CONSOLIDATED_COACH_ONLY_MESSAGE =
  'This report combines more than one Xero organisation, so your coach prepares it. Reports they have saved are under Report History.'
